Add documentation for Google ML & BigQuery nodes
Losant/losant-docs pull request #45
Opened 2017-12-12 22:08 UTC by wesm87

Also changes "Google Pub/Sub" to "GCP Pub/Sub" to match the new naming
convention

2017-12-12 23:36 UTC, cephirothdy2j requested changes

2017-12-12 23:36 UTC, cephirothdy2j commented on docs/workflows/data/google-big-query.md
> +# GCP BigQuery
Add "Node" to the end of this title to be consistent with other nodes in docs.

2017-12-12 23:36 UTC, cephirothdy2j commented on docs/workflows/data/google-big-query.md
> +The GCP (Google Cloud Platform) BigQuery node allows a workflow to interact with Google BigQuery by fetching, creating, updating, or deleting data and optionally store the result on the workflow payl
store => storing (to match tense)

2017-12-12 23:36 UTC, cephirothdy2j commented on docs/workflows/data/google-big-query.md
> +A [service account auth token](https://cloud.google.com/docs/authentication/getting-started#creating_a_service_account) is required for the workflow to authenticate with Google ML. You may enter this
"Google ML"; guessing that was a copy/paste error.

2017-12-12 23:36 UTC, cephirothdy2j commented on docs/workflows/data/google-big-query.md
> +The GCP (Google Cloud Platform) BigQuery node allows a workflow to interact with Google BigQuery by fetching, creating, updating, or deleting data and optionally store the result on the workflow payl
I'd also say "the result of the operation"

2017-12-12 23:36 UTC, cephirothdy2j commented on docs/workflows/data/google-big-query.md
> +The available options here will change depending on the selected resource and action. For example, if the selected action creates or updates a resource then a request body is required that contains t
Change the ampersand (&) to "and"; it's considered bad form to use an ampersand anywhere that is not a proper noun or in a space-constricted headline.

Also. this paragraph ends with a closing parenthesis, but there is no corresponding opening character.

Finally, can you include one example resource/action here with a screenshot of the edit panel and a short explanation? e.g. Tabledata > List

2017-12-12 23:36 UTC, cephirothdy2j commented on docs/workflows/data/google-big-query.md
> +Optionally, you may specify a payload path at which to place the results. If the request succeeds but no result is returned by BigQuery (for example, when deleting a resource)  the result will be `{
The result is not always optional; it depends on the resource/action selected.

2017-12-12 23:36 UTC, cephirothdy2j commented on docs/workflows/data/google-ml.md
> +# GCP ML
Same as BigQuery title comment; add "Node"

2017-12-12 23:36 UTC, cephirothdy2j commented on docs/workflows/data/google-big-query.md
> +The GCP (Google Cloud Platform) BigQuery node allows a workflow to interact with Google BigQuery by fetching, creating, updating, or deleting data and optionally store the result on the workflow payl
Can you add a link to "Google BigQuery" going to one of their pages with a general overview of what the service is? We do that for other nodes that interact with third-party services.

2017-12-12 23:36 UTC, cephirothdy2j commented on docs/workflows/data/google-ml.md
> +The GCP (Google Cloud Platform) ML node allows a workflow to send data to Google ML and store the resulting predictions on the workflow payload.
Like with BigQuery, add a "Google ML" link to one of their pages explaining what the service is.

2017-12-12 23:36 UTC, cephirothdy2j commented on docs/workflows/data/google-ml.md
> +Specify the name of the model for which you want to get predictions. You may optionally specify the model version as well; if no version is provided the model's default version will be used.
Provide a little more info on what a "model" is; or link to a page where Google describes it.

2017-12-12 23:36 UTC, cephirothdy2j commented on docs/workflows/data/google-ml.md
> +The instances path is a payload path that points to the instances data you want to get predictions for.
Provide a little more info on what an "instance path" is; or link to a page where Google describes it.

2017-12-12 23:36 UTC, cephirothdy2j commented on docs/workflows/outputs/google-pub-sub.md
> +# GCP Pub/Sub
Make the same changes you made for this file in the "Google Pub/Sub" trigger as well. (docs/workflows/triggers/google-pub-sub.md and the docs navigation)

2017-12-13 04:09 UTC, cephirothdy2j approved these changes

2017-12-13 15:30 UTC, spacetc62 approved these changes

2017-12-13 15:30 UTC, merged