application archive docs
Losant/losant-docs pull request #47
Opened 2018-01-12 16:07 UTC by eeerin

Should I update all the images on this page to have "archive" in on the menu? Please Proofread! 👍

2018-01-15 16:24 UTC, spacetc62 requested changes

2018-01-15 16:24 UTC, spacetc62 commented on docs/applications/overview.md
> +Application archive is a way to backup an application's devices data on either Amazon S3 or Google Cloud Storage. The archive configuration allows you to specify which devices data should be backed u
I don't think I would call this a "backup" - since eventually, when the data TTLs form losant, it is the *only* copy of the data.

2018-01-15 16:24 UTC, spacetc62 commented on docs/applications/overview.md
> +Application archive is a way to backup an application's devices data on either Amazon S3 or Google Cloud Storage. The archive configuration allows you to specify which devices data should be backed u
I'd add information about *why* it is 31 days, you should be able to link to somewhere else in the docs that talks about the valid date range for reporting data.

2018-01-15 16:24 UTC, spacetc62 commented on docs/applications/overview.md
> +Application archive is a way to backup an application's devices data on either Amazon S3 or Google Cloud Storage. The archive configuration allows you to specify which devices data should be backed u
I'd add an example of the resulting CSV, and an example of the directory structure

2018-01-15 19:44 UTC, cephirothdy2j reviewed
Shouldn't this PR be made against release and not master?

2018-01-16 20:29 UTC, spacetc62 approved these changes

2018-01-16 20:30 UTC, merged